---
title: "Fit_Test_data_03"
author: "Iris Chow"
date: "2025-01-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Testing Data
```{r}
library(dplyr)
library(readr)
testing_env_cov <- read_csv("data_cleaning/testing_data/env_cov.csv")
testing_meta_data <- read_csv("data_cleaning/testing_data/meta_data.csv")
testing_soil_data <- read_csv("data_cleaning/testing_data/soil_data.csv")
testing_weather_season <- read_csv("data_cleaning/testing_data/weather_season.csv")
testing_weather_year <- read_csv("data_cleaning/testing_data/weather_year.csv")
```
# Reformat data
```{r}
trait_data <- read_csv("data_cleaning/training_data/trait_data.csv")
# trait_data
# Remove "Replicate" "Block""Plot""Range" "Pass" "Hybrid_orig_name" "Hybrid_Parent1""Hybrid_Parent2"  
selected_trait_data <- trait_data %>%
  select(-Replicate, -Block, -Plot, -Range, -Pass, -Hybrid_orig_name, -Hybrid_Parent1, -Hybrid_Parent2)

# Display the first few rows of the modified dataframe
head(selected_trait_data)
```

```{r}
# Display the first few rows of the modified dataframe
head(selected_trait_data)
```
```{r}
updated_trait_data <- selected_trait_data %>% mutate(Env1 = sub("_(.*)$", "", Env))
print(updated_trait_data)
```
```{r}
updated_env_cov <- testing_env_cov  %>% mutate(Env1 = sub("_(.*)$", "", Env))
```


```{r}
testing_merged_data <- updated_trait_data %>%
  inner_join(updated_env_cov, by = "Env1")

# Display the first few rows of the merged dataframe
head(testing_merged_data)
```

```{r}
test_condensed_data <- testing_weather_season %>%
  select(-Date) %>%  # Remove the Date column
  group_by(Env) %>%  # Group by Env
  summarise(across(everything(), mean, na.rm = TRUE))  # Calculate the mean for each group

# Display the first few rows of the condensed dataframe
head(test_condensed_data)
```
```{r}
updated_condensed_data <- test_condensed_data  %>% mutate(Env1 = sub("_(.*)$", "", Env))
```

```{r}
# merge merged_data and condensed_data by Env
testing_merged_data2 <- testing_merged_data %>%
  inner_join(updated_condensed_data, by = "Env1")

# Display the first few rows of the merged dataframe
head(testing_merged_data2)
```
```{r}
# select useful columns from meta_data
test_selected_meta_data <- testing_meta_data %>%
  select(Env,Treatment,City,Farm)

# Display the first few rows of the modified dataframe
head(test_selected_meta_data)
```


```{r}
updated_selected_meta_data <- test_selected_meta_data  %>% mutate(Env1 = sub("_(.*)$", "", Env))
```

```{r}
# merge merged_data2 and selected_meta_data by Env
testing_merged_data3 <- testing_merged_data2 %>%
  inner_join(updated_selected_meta_data, by = "Env1")

# Display the first few rows of the merged dataframe
head(testing_merged_data3)
```

```{r}
# put lat and long from the envirotype_input data to the merged_data3
selected_envirotype_input <- 
  envirotype_input %>% 
  select(Env,Latitude, Longitude ) %>%
  group_by(Env) %>%  # Group by Env
  summarise(across(everything(), mean, na.rm = TRUE))  # Calculate the mean for each group

head(selected_envirotype_input)
```
```{r}
updated_selected_envirotype_input <- selected_envirotype_input  %>% mutate(Env1 = sub("_(.*)$", "", Env))
```

```{r}
# merge merged_data3 and selected_envirotype_input by Env
testing_merged_data4 <- testing_merged_data3 %>%
  inner_join(updated_selected_envirotype_input, by = "Env1")

# Display the first few rows of the merged dataframe
head(testing_merged_data4)
```
```{r}
test_selected_soil_data <- testing_soil_data %>%
  select(Env, `%K Sat`, `%Ca Sat`, `%Mg Sat`, `%Na Sat`, `% Sand`, `% Silt`, `% Clay`) %>%
  group_by(Env) %>%
  summarise(across(everything(), ~ mean(.x, na.rm = TRUE)))

# Display the first few rows of the resulting dataframe
head(test_selected_soil_data)
```

```{r}
updated_test_selected_soil_data <- test_selected_soil_data  %>% mutate(Env1 = sub("_(.*)$", "", Env))
```

```{r}
# merge merged_data4 and selected_soil_data by Env
testing_merged_data5 <- testing_merged_data4 %>%
  inner_join(updated_test_selected_soil_data, by = "Env1")

# Display the first few rows of the merged dataframe
head(testing_merged_data5)

write_csv(testing_merged_data5, "testing_merged_data5.csv")
```




